name: Masking Secrets
on: push
jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-not-secret
        name: Generate and output a not-secret
        run: |
          the_not_secret=$((RANDOM))
          echo "not-secret-number=$the_not_secret" >> "$GITHUB_OUTPUT"
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the not-secret number is ${{ steps.sets-a-not-secret.outputs.not-secret-number }}"
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
  generate-an-environment-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
